usr/bin/calligragemini
usr/bin/calligrageminithumbnailhelper
usr/lib/*/calligra/imports/Calligra/Gemini/
usr/lib/*/calligra/imports/org/calligra/CalligraComponents/libcalligraqtquickcomponentsplugin.so
usr/lib/*/calligra/imports/org/calligra/CalligraComponents/qmldir
usr/share/applications/kde4/calligragemini.desktop
usr/share/icons/hicolor/*x*/apps/calligragemini.png
usr/share/kde4/apps/calligragemini
